spring:
  application:
    name: gateway

server:
  port: 8080

#eureka:
#  enabled: false

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    space-auth-api:
      path: /auth/mobile/**
      url: http://auth-api.malangmalang.com:8088
      stripPrefix: false
    space-os-api:
      path: /os/mobile/**
      url: http://os-api.malangmalang.com:8088
      stripPrefix: false
    gateway-client1:
      path: /foos/**
      serviceId: gateway-client1
      stripPrefix: false
    bar-api:
      path: /bars/**
      url: http://localhost:8082
      stripPrefix: false

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000
#    foo-api:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000

#foo-api:
#  ribbon:
#    eureka:
#      enabled: true
#    listOfServers: localhost:8088, localhost:8081
#    ServerListRefreshInterval: 5000 # 서버리스트 캐쉬를 5초로 설정

#gateway-client1:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:8088, localhost:8081
#    ServerListRefreshInterval: 5000 # 서버리스트 캐쉬를 5초로 설정

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
