server:
  port: 8080


ribbon:
  eureka: false

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    space-auth-api:
      path: /auth/mobile/**
      url: http://auth-api.malangmalang.com:8088
      stripPrefix: false
    space-os-api:
      path: /os/mobile/**
      url: http://os-api.malangmalang.com:8088
      stripPrefix: false
    foo-api:
      path: /foos/**
      url: http://localhost:8081
      stripPrefix: false
    bar-api:
      path: /bars/**
      url: http://localhost:8082
      stripPrefix: false
